#!/bin/bash

su root -c "apt-get update -y && apt-get upgrade -y && apt-get install -y sudo && adduser $USER sudo"

sudo apt-get update && apt-get install -y zsh curl git build-essential net-tools
sudo sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
sudo apt-get upgrade -y vim && cd
echo "set number\nsyntax on\n set mouse=a" > .vimrc
